### ISSUE TITLE
Autocomplete Style fixes

### ISSUE THREAD

**Issue by chrisblakley** [chrisblakley/WP-Nebula#719]
Get the IE style fixes for jQuery Autocomplete into Nebula.

Also get the style override for the top distance on :focus updated.
@patphg - can you send me the :focus update for style.css?

**Comment by pmcneil18** [comment]
This is the code added to remove the autocomplete focus jumping. By default it was getting a -1px margin.

```.ui-autocomplete.ui-widget-content li.ui-state-focus,
.ui-autocomplete.ui-widget-content li.ui-state-active{margin:0}```
